version: "3.8"
services:
  backend:
    build: ./transaction
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build: ./bank-frontend
    ports:
      - "80:80"

